name: Index Update
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  #workflow_dispatch: # Autorizes manual execution
    inputs:
      container:
        description: "Container image to use"
        default: null
        # for local execution use: "catthehacker/ubuntu:act-latest"
  issues:
  #schedule:
    #- cron: "59 23 * * *" # Cada dia a les 23:59 (UTC)


jobs:

  update-index:
    runs-on: ubuntu-latest

    container:
      image: "${{github.event.inputs.container}}"
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - name: Add Mask
        run: echo "::add-mask::$GITHUB_TOKEN"

      - name: Checkout code
        uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 5 # Descarga más commits si es necesario

      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "latest"

      - name: Find repositories data
        run: |
          node
          ./scripts/update_index.js

      - name: Commit and push if changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Debug: List files in assets/
          echo "--- Files in assets/ ---"

          ls ./src/assets -la

          # Only commits on changes
          if [ -n "$(git diff ./src/assets/data.json)" ]; then
            git add ./src/assets/data.json
            git commit -m "Updates data.json on ${{ github.event_name }} event"
            git push
          else
            echo "No changes"
          fi
