name: Index Update
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  #workflow_dispatch: # Permet activació manual
    inputs:
      container:
        description: "Container image to use"
        required: false
        default: "PEPE" # "catthehacker/ubuntu:act-latest"
  issues:
  #schedule:
    #- cron: "59 23 * * *" # Cada dia a les 23:59 (UTC)


jobs:

  update-index:
    runs-on: ubuntu-latest

    container:
      image: "${{github.event.inputs.container}}" # catthehacker/ubuntu:act-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - name: Add Mask
        run: |
          echo "${{github.event.inputs.container}}"
          echo "::add-mask::$GITHUB_TOKEN"
          echo "CONTAINER: ${{github.event.inputs.container}}"
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3
#        with:
      #     fetch-depth: 5 # Descarga más commits si es necesario

      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "latest"

      - name: Find description
        run: |
          node
          ./scripts/update_index.js
      # - name: Run commit logger script
      #   run: |
      #     mkdir -p log/  # Asegura que el directorio existe
      #     cd scripts
      #     go run log_commits.go || exit 1  # Falla el job si el script falla

      - name: Commit and push if changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Debug: Listar archivos en assets/
          echo "--- Archivos en assets/ ---"
          ls -la

      #     # Solo commitea si hay cambios
      #     if [ -n "$(find log/ -type f -name 'commits_*.txt')" ]; then
      #       git add log/
      #       git commit -m "Auto: Add latest commits log"
      #       git push
      #     else
      #       echo "No hay archivos nuevos en log/ para commitear."
      #     fi
