name: Index Update
on:
  push:
    branches: ["main"]
  label:
  workflow_dispatch:
  #workflow_dispatch: # Autorizes manual execution
    inputs:
      local:
        description: "Using Github local actions"
        default: null
        # for local execution use: "true"
      container:
        description: "Container image to use"
        default: null
        # for local execution use: "catthehacker/ubuntu:act-latest"

  schedule:
    - cron: "59 23 * * *" # Every day on 23:59 (UTC)

jobs:

  update-index:
    runs-on: ubuntu-latest

    container:
      image: "${{github.event.inputs.container}}"

    steps:
    #   - name: Add Mask
    #     run: echo "::add-mask::$GITHUB_TOKEN"

      - name: Checkout code
        uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 5 # Descarga más commits si es necesario

      #- name: Set up Node
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: "latest"

      - name: Install @actions/core data
        run: npm i @actions/core

      - name: Find repositories data
        run: ./scripts/update_index.js
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN has not Variables permission.
          PAT_GITHUB_TOKEN: ${{ secrets.PAT_GITUB_TOKEN }}

      - name: Commit and push data.json if changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote -v

          # Debug: List files in assets/
          echo "--- Files in assets/ ---"
          #ls ./src/assets -la

          #cat ./src/assets/data.json

          # Only commits on changes
          if [ -n "$(git diff ./src/assets/data.json)" ]; then
            git add ./src/assets/data.json
            git commit -m "Updates data.json on ${{ github.event_name }} event"
            if [ "${{ github.event.inputs.local }}" = "true" ]; then
                echo "LOCAL DATA.JSON PUSH"
                git push https://${{ secrets.GITHUB_TOKEN }}@github.com/manuelgarciacr/index.git
            else
                echo "HOSTED DATA.JSON PUSH"
                git push https://github.com/manuelgarciacr/index.git
            fi
          else
            echo "No data.json changes"
          fi
  final-message:
    runs-on: ubuntu-latest
    needs: [update-index]
    steps:
      - name: Generate final message
        run: |
          echo "The workflow has completed with the following status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          if [ ${{ job.status }} == "success" ]; then
            echo "::set-output name=status::Success"
          else
            echo "::set-output name=status::Failure"
          fi
