name: Index Update

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Permet activació manual
  #schedule:
    #- cron: "59 23 * * *" # Cada dia a les 23:59 (UTC)

jobs:
  update-index:
    runs-on: ubuntu-latest
#    container:
#      image: catthehacker/ubuntu:act-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - name: Add Mask
        run: |
          echo "::add-mask::$GITHUB_TOKEN"

      - name: Checkout code
        uses: actions/checkout@v3
#        with:
      #     fetch-depth: 5 # Descarga más commits si es necesario

      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "latest"

      - name: Find description
        run: |
          node
          git --version
          ./scripts/update_index.js
      # - name: Run commit logger script
      #   run: |
      #     mkdir -p log/  # Asegura que el directorio existe
      #     cd scripts
      #     go run log_commits.go || exit 1  # Falla el job si el script falla

      # - name: Commit and push if changes
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"

      #     # Debug: Listar archivos en log/
      #     echo "--- Archivos en log/ ---"
      #     ls -la log/

      #     # Solo commitea si hay cambios
      #     if [ -n "$(find log/ -type f -name 'commits_*.txt')" ]; then
      #       git add log/
      #       git commit -m "Auto: Add latest commits log"
      #       git push
      #     else
      #       echo "No hay archivos nuevos en log/ para commitear."
      #     fi
